name: Gestion de contenu d'un site php, utilisant Mysql DB sur Docker et Ubuntu

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du repository
    - name: Checkout du repository
      uses: actions/checkout@v2
      
    # Setup du PHP, des extensions et de Composer
          
    # Installation des dépendances de Composer
    - name: Installation des dépendances de Composer
      run: composer install
      working-directory: ./

    # Build et run du Docker containers
    - name: Build et run du Docker containers
      run: |
        docker-compose up --build -d
      working-directory: ./

    # Déploiement
    - name: Déploiement
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
